server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: Tomatos
    password: 20030503
  redis:
    host: 127.0.0.1
    port: 6379
    password: zjlljz
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug