---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Tomatos.
--- DateTime: 2025/5/26 19:42
---

local lockKey = KEYS[1]
local threadId = ARGV[1]
local releaseTime = ARGV[2]

-- 如果用户表不存在，先创建一个用户表，并添加线程锁和线程锁有效时间
if redis.call('EXISTS', lockKey) == 0 then
    redis.call('HSET', lockKey, threadId, '1')
    redis.call('EXPIRE', lockKey, releaseTime); -- 1 hour
    return 1
end

-- 用户表中存在对应的线程锁，使用数量计数器加1
if (redis.call('HEXISTS', lockKey, threadId) == 1) then
    redis.call('HINCRBY', lockKey, threadId, '1')
    redis.call('EXPIRE', lockKey, releaseTime);
    return 1;
end

return 0