--- 返回值说明:
--- 0: 表示抢优惠券成功
--- 1: 表示剩余库存不足
--- 2: 表示已经抢过该优惠券
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Tomatos.
--- DateTime: 2025/5/27 17:19
---

local voucherId = ARGV[1]
local userId = ARGV[2]

local voucherStockKey = 'seckill:stock:' .. voucherId --- 字符串拼接
local voucherKey = 'seckill:voucher:' .. voucherId

--- 判读是否已领取当前优惠券
if redis.call('SISMEMBER', voucherKey, userId) == 1 then
    return 2
end

--- 判断当前优惠券是否还有库存
local remainStock = tonumber(redis.call('GET', voucherStockKey))
if not remainStock or remainStock <= 0 then
    return 1
end

redis.call('INCRBY', voucherStockKey, -1)
redis.call('SADD', voucherKey, userId)
return 0