---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Tomatos.
--- DateTime: 2025/5/27 17:19
---

local voucherId = ARGV[1]
local userId = ARGV[2]

local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

local remainStock = tonumber(redis.call('GET', stockKey))
if not remainStock or remainStock <= 0 then
    return 1
end

if redis.call('SISMEMBER', orderKey, userId) == 1 then
    return 2
end

redis.call('INCRBY', stockKey, -1)
redis.call('SADD', orderKey, userId)

return 0








