---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Tomatos.
--- DateTime: 2025/5/26 21:06
---
local lockKey = KEYS[1]
local threadId = ARGV[1]

-- 如果对应的线程锁已经不存在了不进行任何操作
if redis.call('HEXISTS', lockKey, threadId) == 0 then
    return 0
end
-- 线程锁的持有述减少1
local count = redis.call('HINCRBY', lockKey, threadId, -1)
-- 当持有数变为0的时候说明这个时候是最顶层的调用
if count == 0 then
    redis.call('DEL', lockKey);
end

return 1